### ISSUE TITLE
what does the channel mean ? 

### ISSUE THREAD

**Issue by helxsz** [mainflux/mainflux-core#1]
quite interested, just have a question, how do we use the channel with redis , any use cases ?

**Comment by nmarcetic** [comment]
Hi @helxsz Channels are like streams for devices, device can create channel and send's data to this channel. Then you can subscribe to this channel over MQTT and get channel data in real time.
Please checkout our Get started page https://github.com/Mainflux/mainflux/wiki/HTTP-Getting-Started

Do you have any special need for Redis ?

**Comment by drasko** [comment]
@helxsz think of channels like a communication cables between your devices and applications. Messages  flow though the channels bidirectionally - sensors measurements are pushed into the channel toward the applications, and command are pushed into the channels towards the devices (actuators).

Several devices/applications can publish on the same channel.

Internally channels are mapped to MQTT topics, so "listening on a channel" is equivalent to MQTT SUB and writing into the channel is equivalent to MQTT PUB. Difference is that:
- Channels are multi-protocol relayed, so HTTP PUT is published via MQTT and WS also (as a PUB)
- Channles are persisted - all messages flowing through channels are persisted internaly in time-series database

Messages that flow though channels are by convention in [SenML](https://tools.ietf.org/html/draft-ietf-core-senml-04) format.

**Comment by drasko** [comment]
@helxsz can this one be closed?
